### ISSUE TITLE
Support CodeLen

### ISSUE THREAD

**Issue by 45degree** [glepnir/lspsaga.nvim#282]
`CodeLen` has been a part of `LSP` standard specification for a while now, some `LSP` such as `ccls` also implement it, so, can `lspsage` support the feature?

**Describe the solution you'd like**
I know another plugin [navigator](https://github.com/ray-x/navigator.lua) has supported it and this is the example,
![navigator codelen](https://user-images.githubusercontent.com/1681295/132429134-abc6547e-79cc-44a4-b7a9-23550b895e51.jpg)

**Comment by glepnir** [comment]
Okay. it will be support:)

**Comment by rhcher** [comment]
Hi, sorry for later, because I work on this recently and want to know what's your exactly means about codelens feature. Codelens can also be execute as codeaction and I assume what you want is just a UI like codeaction in lspsaga? Do you know any language server can provide the case that multi codelens one line? Because if it's only one codelens and this feature will slow down efficiency instead of the opposite.
BTW, the ccls's codelens have no effect after execution, it's just same as vim.lsp.codelens.run() and I need to look into it.

**Comment by 45degree** [comment]
> Codelens can also be execute as codeaction and I assume what you want is just a UI like codeaction in lspsaga? 

yes, I mean the UI.

>  Do you know any language server can provide the case that multi codelens one line? 

Sorry, I didn't notice if any language server provided this feature.
