### ISSUE TITLE
Q: change float window size to a relative percent value of buffer window size

### ISSUE THREAD

**Issue by bryceyang** [glepnir/lspsaga.nvim#77]
for me, the preview window of references is too narrow to catch content.

<img width="1373" alt="Screen Shot 2021-02-06 at 11 09 11 PM" src="https://user-images.githubusercontent.com/9302617/107122112-bdb25780-68d0-11eb-876b-41493ddc34f5.png">

how can i change the preview windows size?

**Comment by glepnir** [comment]
use `max_finder_preview_lines = 10`  to change your expect preview line count . and support scroll down or up preview window, defaul keymaps,
```
finder_action_keys = {
 open = 'o', vsplit = 's',split = 'i',quit = 'q',scroll_down = '<C-f>', scroll_up = '<C-b>'
},
```

**Comment by bryceyang** [comment]
@glepnir  does `max_finder_preview_lines` only controls the preview lines? how about changing preview line width?

**Comment by glepnir** [comment]
>  how about changing preview line width?

what do you mean the width will auto change according the win width

**Comment by ray-x** [comment]
@glepnir  There is a typo in the options 
should be `max_finder_preview_lines` instead of `max_finder_preview_lins`

I agree that the width should be configurable. 

For a narrow window.  The window is a bit too narrow (it is fine, but I would say better to be wider as code preview only ~30 cols in a row, lots of lines was broken make it hard to read). 

![Screen Shot 2021-02-09 at 9 46 03 am](https://user-images.githubusercontent.com/1681295/107291122-c0bd6b80-6abb-11eb-82dd-12b319a5ed5b.png)

For a wide screen, it a bit odd....
![Screen Shot 2021-02-09 at 9 17 48 am](https://user-images.githubusercontent.com/1681295/107291184-df236700-6abb-11eb-87be-e4eece04010c.png)
I really like line wrap in the preview. But there is still plenty of spaces. Would be great to be able setup preview window size so it could make better use of the empty space in widescreen.  Personally, I would prefer a preview width of 80% of available space, or, if someone coding in python, the PEP requirement of 80 cols, it is also fine for me.

**Comment by glepnir** [comment]
I had improve it

**Comment by ray-x** [comment]
Spotted something
``` lua
    if pad_right > 25 then
      opts.col = finder_win_opts.col+width+2
      opts.row = finder_win_opts.row
      opts.width = min_width + 20
      opts.height = self.definition_uri + self.reference_uri + 6
    elseif pad_right > 10 and pad_right < 25 then
      opts.col = finder_win_opts.col+width+2
      opts.row = finder_win_opts.row
      opts.width = min_width + 5
      opts.height = self.definition_uri + self.reference_uri + 6
    elseif pad_right < 10 and pad_right > 0 then
      opts.col = finder_win_opts.col+width+2
      opts.row = finder_win_opts.row
      opts.width = min_width
      opts.height = self.definition_uri + self.reference_uri + 6
    elseif pad_right < 0 then
      opts.row = finder_win_opts.row + height + 2
      opts.col = finder_win_opts.col
      opts.width = min_width
      opts.height = 8
      if self.WIN_HEIGHT - height - opts.row < 4 then
        return
      end
    end

```

I think you missed boundary check for pad_right==0, pad_right==10,pad_right==25.

Also can we do this?
```lua
    if pad_right >= 25 then
      opts.col = finder_win_opts.col+width+2
      opts.row = finder_win_opts.row
      opts.width = min_width + math.min(math.max(pad_right/2, 20), 60) 
      opts.height = self.definition_uri + self.reference_uri + 6
```

**Comment by glepnir** [comment]
These values ​​are arbitrary. I simply found some values ​​that can judge some windows, so they are unscientific. I haven't thought of how to better calculate pad right.

**Comment by ray-x** [comment]
The issue need to be fixed for the pad_right.
The  following values `pad_right==0; pad_right==10; pad_right==25.` will escape your if/eleseif/else branch and it will trigger an error

``` vim
Error executing vim.schedule lua callback: ....cache/dein/.cache/init.vim/.dein/lua/lspsaga/window.lua:192: 'width' key must be a positive Integer  
```
The code should looks like this, be care of the boundary ( >= instead of > etc):
```lua
    if pad_right >= 25 then
       ...
    elseif pad_right >= 10 and pad_right < 25 then
        ...
    elseif pad_right < 10 and pad_right >= 0 then
```

**Comment by ray-x** [comment]
personally, the following code snippets works for me. tested different width. No overlap nor errors.

```lua
    if pad_right >= 0 then
      opts.col = finder_win_opts.col+width+2
      opts.row = finder_win_opts.row
      opts.width = min_width + math.max(0, math.min(math.floor((pad_right-10)/1.5), 60))
      opts.height = self.definition_uri + self.reference_uri + 6
    elseif pad_right < 0 then
      opts.row = finder_win_opts.row + height + 2
      opts.col = finder_win_opts.col
      opts.width = min_width
      opts.height = 8
      if self.WIN_HEIGHT - height - opts.row < 4 then
        return
      end
    end
```

**Comment by glepnir** [comment]
I will test it

**Comment by glepnir** [comment]
tested . LGTM  Thanks.
