### ISSUE TITLE
Opening the finder causes syntax highlighting to change?

### ISSUE THREAD

**Issue by samtgarson** [glepnir/lspsaga.nvim#962]
### Describe the bug

Opening the finder causes syntax highlighting to change. Very strange behaviour, visible here:

https://user-images.githubusercontent.com/6242344/227183058-7f7c9fc7-d3d6-4917-9d37-809041d08394.mov

`syntax`, `colorscheme` and `filetype` are all correct before and after the change. Are you aware of anything that might cause this? It wasn't happening before I updated to the latest version of this plugin.

### Steps to reproduce

Install the plugin and tokyonight, this is run on a Typescript file. Can provide minimal recreation or further details if needed

### Expected behavior

The highlighting does not change.

### Neovim version (nvim -v)

NVIM v0.8.3

### lspsaga commit

44ae62d

### Terminal name/version

iTerm2, Build 3.4.19

**Comment by glepnir** [comment]
oh it need disable syntax when close finder  in `0.8.3` . but currently the finder had rewrite in next version . so probably you need wait the next version merge ...because most bugfix I do it in new version ..

![image](https://user-images.githubusercontent.com/41671631/227185078-051f1506-bfed-4e7f-ae32-aee9334d83cb.png)

**Comment by samtgarson** [comment]
Ok, no problem, thanks. Shall I leave this open until the next version lands?
