### ISSUE TITLE
option to make finder window absolute center

### ISSUE THREAD

**Issue by tami5** [glepnir/lspsaga.nvim#99]
All the other popup are right to be relative but this one needs to be absolute center, at least as an option

**Comment by glepnir** [comment]
window of lsp_finder?

**Comment by tami5** [comment]
yep

**Comment by glepnir** [comment]
Currently it is not absolutely centered, because there are some issues related to the automatic preview window. When the window is wide enough, the preview window is displayed on the right side of the finder,
When the window width is not enough, but the height is enough, the preview window will be displayed at the bottom, when the right and bottom widths are not enough, the preview window will not be displayed
